In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

class SimpleNN:
    def __init__(self, input_size, hidden_size1, hidden_size2, output_size):
        self.hidden_weights1 = np.random.randn(input_size, hidden_size1)
        self.hidden_bias1 = np.zeros((1, hidden_size1))
        self.hidden_weights2 = np.random.randn(hidden_size1, hidden_size2)
        self.hidden_bias2 = np.zeros((1, hidden_size2))
        self.output_weights = np.random.randn(hidden_size2, output_size)
        self.output_bias = np.zeros((1, output_size))

    def forward(self, X):
        #propagacja przednia przez hidden layer1
        self.hidden_layer_input1 = np.dot(X, self.hidden_weights1) + self.hidden_bias1
        self.hidden_layer_output1 = sigmoid(self.hidden_layer_input1)
        
        #propagacja przednia przez hidden layer2
        self.hidden_layer_input2 = np.dot(self.hidden_layer_output1, self.hidden_weights2) + self.hidden_bias2
        self.hidden_layer_output2 = sigmoid(self.hidden_layer_input2)
        
        #propagacja przednia przez output layer
        self.output_layer_input = np.dot(self.hidden_layer_output2, self.output_weights) + self.output_bias
        self.output = sigmoid(self.output_layer_input)
        
        return self.output

    def backward(self, X, y, output):
        #obliczanie errroru   |0.3 - 1|^2
        output_error = y - output
        output_delta = output_error * sigmoid_derivative(output)

        #blad dla drugiej warstwy ukrytej
        hidden_error2 = output_delta.dot(self.output_weights.T)
        hidden_delta2 = hidden_error2 * sigmoid_derivative(self.hidden_layer_output2)

        #blad dla pierszej warstwy ukrytej
        hidden_error1 = hidden_delta2.dot(self.hidden_weights2.T)
        hidden_delta1 = hidden_error1 * sigmoid_derivative(self.hidden_layer_output1)

        #aktualizacja wag i biasow
        self.output_weights += 0.1 * self.hidden_layer_output2.T.dot(output_delta)
        self.output_bias += 0.1 * np.mean(output_delta, axis=0, keepdims=True)

        self.hidden_weights2 += 0.1 * self.hidden_layer_output1.T.dot(hidden_delta2)
        self.hidden_bias2 += 0.1 * np.mean(hidden_delta2, axis=0, keepdims=True)

        self.hidden_weights1 += 0.1 * X.T.dot(hidden_delta1)
        self.hidden_bias1 += 0.1 * np.mean(hidden_delta1, axis=0, keepdims=True)

    def train(self, X, y, epochs=1000):
        for _ in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

    def predict(self, X):
        return self.forward(X)


In [4]:
    import numpy as np
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    y = np.array([[0], [1], [1], [0]])

    nn = SimpleNN(input_size=2, hidden_size1=4, hidden_size2=4, output_size=1)

    nn.train(X, y, epochs=10000)

    # nn.forward(X)
    # nn.backward(X, y, nn.forward(X))

    predictions = nn.predict(X)
    print(predictions)

[[-0.01392439]
 [ 0.10236862]
 [ 0.10154139]
 [-0.01888009]]
[[-0.01487356]
 [ 0.10466192]
 [ 0.10397395]
 [-0.02000291]]
[[-0.015892  ]
 [ 0.10697858]
 [ 0.10643229]
 [-0.02119592]]
[[-0.01698369]
 [ 0.10931256]
 [ 0.10890953]
 [-0.02246212]]
[[-0.01815254]
 [ 0.11165705]
 [ 0.11139786]
 [-0.02380433]]
[[-0.01940231]
 [ 0.11400448]
 [ 0.11388861]
 [-0.02522505]]
[[-0.02073651]
 [ 0.11634655]
 [ 0.11637221]
 [-0.02672645]]
[[-0.02215833]
 [ 0.11867424]
 [ 0.1188383 ]
 [-0.02831021]]
[[-0.02367048]
 [ 0.12097793]
 [ 0.12127577]
 [-0.0299775 ]]
[[-0.02527513]
 [ 0.12324742]
 [ 0.12367287]
 [-0.03172882]]
[[-0.02697375]
 [ 0.12547211]
 [ 0.12601738]
 [-0.03356395]]
[[-0.028767  ]
 [ 0.12764112]
 [ 0.12829678]
 [-0.03548184]]
[[-0.03065464]
 [ 0.12974347]
 [ 0.13049843]
 [-0.03748055]]
[[-0.03263539]
 [ 0.13176829]
 [ 0.13260986]
 [-0.03955718]]
[[-0.03470684]
 [ 0.13370499]
 [ 0.13461898]
 [-0.04170784]]
[[-0.03686544]
 [ 0.13554354]
 [ 0.13651437]
 [-0.04392761]]
[[-0.03910641]
 [ 0.1372