In [131]:
import numpy as np

# Funkcja aktywacji - Sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Pochodna funkcji Sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

class SimpleNN:
    def __init__(self, input_size, hidden_size1, hidden_size2, output_size):
        self.hidden_weights1 = np.random.randn(input_size, hidden_size1)
        self.hidden_bias1 = np.zeros((1, hidden_size1))
        self.hidden_weights2 = np.random.randn(hidden_size1, hidden_size2)
        self.hidden_bias2 = np.zeros((1, hidden_size2))
        self.output_weights = np.random.randn(hidden_size2, output_size)
        self.output_bias = np.zeros((1, output_size))

    def forward(self, X):
        # Propagacja przednia przez pierwszą warstwę ukrytą
        self.hidden_layer_input1 = np.dot(X, self.hidden_weights1) + self.hidden_bias1
        self.hidden_layer_output1 = sigmoid(self.hidden_layer_input1)
        
        # Propagacja przednia przez drugą warstwę ukrytą
        self.hidden_layer_input2 = np.dot(self.hidden_layer_output1, self.hidden_weights2) + self.hidden_bias2
        self.hidden_layer_output2 = sigmoid(self.hidden_layer_input2)
        
        # Propagacja przednia przez warstwę wyjściową
        self.output_layer_input = np.dot(self.hidden_layer_output2, self.output_weights) + self.output_bias
        self.output = sigmoid(self.output_layer_input)
        
        return self.output

    def backward(self, X, y, output):
        # Obliczanie błędu wyjścia
        output_error = y - output
        output_delta = output_error * sigmoid_derivative(output)
        # Błąd dla drugiej warstwy ukrytej
        hidden_error2 = output_delta.dot(self.output_weights.T)
        hidden_delta2 = hidden_error2 * sigmoid_derivative(self.hidden_layer_output2)

        # Błąd dla pierwszej warstwy ukrytej
        hidden_error1 = hidden_delta2.dot(self.hidden_weights2.T)
        hidden_delta1 = hidden_error1 * sigmoid_derivative(self.hidden_layer_output1)

        # Aktualizacja wag i biasów
        learning_rate = 0.1  # Ustawienie współczynnika uczenia
        self.output_weights += 0.1 * self.hidden_layer_output2.T.dot(output_delta)
        self.output_bias += 0.1 * np.sum(output_delta, axis=0, keepdims=True)
        self.hidden_weights2 += 0.1 * self.hidden_layer_output1.T.dot(hidden_delta2)
        self.hidden_bias2 += 0.1 * np.sum(hidden_delta2, axis=0, keepdims=True)
        self.hidden_weights1 += 0.1 * X.T.dot(hidden_delta1)
        self.hidden_bias1 += 0.1 * np.sum(hidden_delta1, axis=0, keepdims=True)

    def train(self, X, y, epochs=1000):
        for _ in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

    def predict(self, X):
        return self.forward(X)


In [130]:
    import numpy as np
    # Dane treningowe: XOR
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    y = np.array([[0], [1], [1], [0]])

    # Inicjalizacja sieci neuronowej
    nn = SimpleNN(input_size=2, hidden_size1=4, hidden_size2=4, output_size=1)

    # Trenowanie sieci
    nn.train(X, y, epochs=10000)

    # Przewidywanie
    predictions = nn.predict(X)
    print("Przewidywania po treningu:")
    print(predictions)

[[-0.10421984]
 [ 0.13927116]
 [ 0.14284384]
 [-0.09784606]]
[[-0.10522247]
 [ 0.13870992]
 [ 0.14238675]
 [-0.09890688]]
[[-0.10618113]
 [ 0.13815609]
 [ 0.14193068]
 [-0.09992308]]
[[-0.10709737]
 [ 0.13761087]
 [ 0.14147717]
 [-0.10089603]]
[[-0.10797272]
 [ 0.13707526]
 [ 0.14102759]
 [-0.10182714]]
[[-0.10880872]
 [ 0.1365501 ]
 [ 0.14058312]
 [-0.10271783]]
[[-0.10960691]
 [ 0.13603611]
 [ 0.1401448 ]
 [-0.10356953]]
[[-0.11036879]
 [ 0.13553384]
 [ 0.1397135 ]
 [-0.10438369]]
[[-0.11109587]
 [ 0.13504375]
 [ 0.13928998]
 [-0.10516173]]
[[-0.11178959]
 [ 0.13456619]
 [ 0.13887488]
 [-0.10590506]]
[[-0.1124514 ]
 [ 0.13410142]
 [ 0.1384687 ]
 [-0.10661507]]
[[-0.11308266]
 [ 0.13364961]
 [ 0.13807188]
 [-0.10729313]]
[[-0.11368474]
 [ 0.13321085]
 [ 0.13768474]
 [-0.10794055]]
[[-0.11425892]
 [ 0.13278518]
 [ 0.13730755]
 [-0.10855863]]
[[-0.11480648]
 [ 0.13237256]
 [ 0.13694048]
 [-0.10914863]]
[[-0.11532863]
 [ 0.13197294]
 [ 0.13658366]
 [-0.10971176]]
[[-0.11582652]
 [ 0.1315